<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPokKGX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPokKGX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPokKGX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPokKGX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFPokKGX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FPokKGX',
    'container.build_id' => '4f2745d4',
    'container.build_time' => 1551454461,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPokKGX');
