<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNwnvKo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNwnvKo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVNwnvKo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVNwnvKo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVNwnvKo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VNwnvKo',
    'container.build_id' => 'df8c2424',
    'container.build_time' => 1550503680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNwnvKo');
