<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRq4eB1e\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRq4eB1e/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRq4eB1e.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRq4eB1e\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRq4eB1e\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Rq4eB1e',
    'container.build_id' => 'f042d29e',
    'container.build_time' => 1549899540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRq4eB1e');
